Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/sds-adv-ml-t6Z6UgPC-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/sds-adv-ml-t6Z6UgPC-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/sds-adv-ml-t6Z6UgPC-py3.9/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/sds-adv-ml-t6Z6UgPC-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/sds-adv-ml-t6Z6UgPC-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/sds-adv-ml-t6Z6UgPC-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# オセロモジュールのインポート
import othello
from othello import Move, Player
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;66;03m# オセロモジュールのインポート[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mothello[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mothello[39;00m [38;5;28;01mimport[39;00m Move, Player

File [0;32m~/work/1284-sds-ml-advanced/1284-sds-ml-advanced/contents/sec3/othello/__init__.py:1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mothello[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

File [0;32m~/work/1284-sds-ml-advanced/1284-sds-ml-advanced/contents/sec3/othello/othello.py:14[0m
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mPIL[39;00m [38;5;28;01mimport[39;00m Image, ImageDraw
[1;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpylabtools[39;00m [38;5;28;01mimport[39;00m print_figure
[0;32m---> 14[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcutils[39;00m [38;5;28;01mimport[39;00m cython_step, cython_is_legal_move
[1;32m     16[0m Board [38;5;241m=[39m npt[38;5;241m.[39mNDArray[np[38;5;241m.[39mobject_]
[1;32m     18[0m __all__ [38;5;241m=[39m [[38;5;124m"[39m[38;5;124mPlayer[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mMove[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmake[39m[38;5;124m"[39m]

[0;31mModuleNotFoundError[0m: No module named 'othello.cutils'

